name: Check issue content
on: 
  issues:
    types: [opened,edited]
jobs: 
  checkIssueContent:
    name: Check for missing information
    runs-on: ubuntu-latest
    env:
      #The 'content_analysis_response' variable is used to store the script response on step one, 
      #and then checked on step two to know if adding any labels is necessary.
      #The initial 'undefined' value will be overridden when the script runs.
      content_analysis_response: undefined
    steps:
      - uses: actions/checkout@v2
      - name: Remove conflicting chars
        uses: frabert/replace-string-action@v1.2
        id: remove_quotations
        with:
          pattern: "\""
          string: ${{ github.event.issue.body }}
          replace-with: '-'
      - name: Check Information
        id: check-info
        run: |
          echo "content_analysis_response=$(pwsh .\\.github\\scripts\\content_identifier.ps1 "${{ steps.remove_quotations.outputs.replaced }}" )" >> $GITHUB_ENV
      - name: Label issue
        if: env.content_analysis_response != 'Valid'
        run: |
          curl -v -u admin:${{ secrets.TOKEN }} -d '{"labels": [${{env.content_analysis_response}}]}' ${{ github.event.issue.url }}/labels
  
