name: Cherry picking
on:
  push:
    branches:
      - master
jobs:
  cherry_pick:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Cp
      run: |
        echo "$(pwsh .\\.github\\scripts\\cherry_pick.ps1 "cherry-test" "${{github.event.after}}" )"
