name: Cherry picking
on:
  push:
    branches:
      - master
jobs:
  cherry_pick:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Cp
      run: |
        git config user.email "astul.betizagasti@globant.com
        git config user.name "Astul-Betizagasti"
        git fetch --all
        git checkout -b cherry-test origin/cherry-test
        git cherry-pick ${{github.event.after}}
        git push origin cherry-test
