name: PR for release branch
on:
  push:
    branches:
      - master
jobs:
  release_pull_request:
    runs-on: ubuntu-latest
    name: release_pull_request
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: Cherry-pick
      run: |
        echo "$(pwsh .\\.github\\scripts\\cherry_pick.ps1 "cherry-test" "${{github.event.after}}" )"
