name: Cherry picking
on:
  push:
    branches:
      - master
jobs:
  cherry_pick:
    runs-on: ubuntu-latest
    env:
      user_email: astul.betizagasti@globant.com
      user_name: Astul-Betizagasti
      cherry_pick_command: 'git cherry-pick -x ${{github.event.after}} --strategy-option theirs'
      destination_branch: 'cherry-test'
    
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Content tests 
      run: |
        echo "${{github.event.commits[0]}}"
        echo "${{github.event.commits[0].message}}"
        echo "${{github.event.commits[0].description}}"
        echo "${{github.event.commits[1]}}"
        echo "${{github.event.commits[1].message}}"
        echo "${{github.event.commits[2].message}}"

    - name: Cherry pick
      run: |
        git config user.email ${{env.user_email}}
        git config user.name ${{env.user_name}}
        git fetch --all
        git checkout -b ${{env.destination_branch}} origin/${{env.destination_branch}}
        ${{env.cherry_pick_command}}
        git push origin ${{env.destination_branch}}
