name: Close stale issues
on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - name: close stale issues
      uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        #this message is requiered but never used.
        stale-issue-message: "."
        skip-stale-issue-message: true
        close-issue-message: "Given that there has been no additional information added, 
        this issue will be closed for now. Please reopen and provide additional 
        information if you wish the Dynamo team to investigate further."
        days-before-stale: 30
        days-before-close: 0
        only-labels: 'needs more info'
