name: Close stale issues
on:
  schedule:
  - cron: "* * * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - name: close stale issues
      uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        skip-stale-issue-message: true
        close-issue-message: "Closing issue for missing info"
        days-before-stale: 1
        days-before-close: 20
        only-labels: 'needs more info'
