name: Move issue

on: 
  issues:
    types: [opened]

jobs: 
  gitIssueCreation:
    name: Git Move Demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Move
        run: hub issue transfer ${{github.event.issue.number}} IssueTest2
