name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "*/2 * * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        skip-stale-issue-message: true
        close-issue-message: "Closing issue for missing info"
        days-before-stale: 1
        days-before-close: 20
        only-labels: 'needs more info'
